version: '3'
services:
    mysql:
        container_name: 'my'
        image: 'mysql:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mysql-db:/var/lib/mysql'
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
volumes:
    mysql-db:
        driver: local
